### ISSUE TITLE
请教一下，能识别圆形的小程序二维码吗？

### ISSUE THREAD

**Issue by Leadrive** [leidenglai/opencv-js-qrcode#1]
你的demo，只截取左上角，想测试下是否支持圆形、线条型的二维码
![1485982252__8393d5fa6b9041fb8c5137cd1c2c618d](https://user-images.githubusercontent.com/16882802/224475021-c3f218fa-5810-400c-ae75-14e02350e762.jpeg)

**Comment by leidenglai** [comment]
肯定不行噻，需要去找识别引擎了

**Comment by snowman** [comment]
what does mean of `只截取左上角`

**Comment by leidenglai** [comment]
> what does mean of `只截取左上角`

因为发票的二维码在左上角
