### ISSUE TITLE
能否支持在 Nodejs 服务端运行

### ISSUE THREAD

**Issue by MrChen2016-08-27** [leidenglai/opencv-js-qrcode#10]
想在 Nodejs 云端运行一个opencv + wechat_qrcode 解析二维码的微服务 给多个项目使用，在 NodeJS 引入后启动时报错:
 "Uncaught TypeError TypeError: fetch failed"。

**Comment by leidenglai** [comment]
这是基于WebAssembly编译的包，服务端是不支持的。
