### ISSUE TITLE
实例化两次会报错{node: undefined, errno: 20, message: 'FS error', stack: '<generic error, no stack>', setErrno: ƒ}

### ISSUE THREAD

**Issue by anxin53** [leidenglai/opencv-js-qrcode#4]
在vue组件中销毁重建就会造成opencv实例化两次就会报错ensureErrnoError函数里面的错误，{node: undefined, errno: 20, message: 'FS error', stack: '<generic error, no stack>', setErrno: ƒ}
![opencv](https://github.com/leidenglai/opencv-js-qrcode/assets/98022733/8432f382-15da-45db-96bc-261d50ed3fb3)

**Comment by luyingjia** [comment]
请问该问题解决了吗

**Comment by anxin53** [comment]
> 请问该问题解决了吗

挂载window上

**Comment by luyingjia** [comment]
> > 请问该问题解决了吗
> 
> 挂载window上

感谢大哥，我以为已经没人会回答了呢，泪目
