### ISSUE TITLE
在vue中如何使用

### ISSUE THREAD

**Issue by JMing96** [leidenglai/opencv-js-qrcode#5]
你好，我在vue中使用时出现了这样的错误，TypeError: Cannot read properties of undefined (reading 'detectAndDecode')
![35a2a93d15dd91ee27d424167722889f](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/a4c49ac3-c388-4c90-b5c5-dac3a1b866d7)
![d1a921b265ffa6ec7e81723c051f4f89](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/6b4d7782-8a1b-4c8b-a2db-4b3a139a7019)
![f3adebb4946bc39581e36c0b6aab629a](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/4e36e5e0-d867-4aa2-a8b2-34e337a6287a)
![884b95a51adb49aa535c43df4a342838](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/deef55a2-d778-4ab1-940d-6db3698b50a2)

**Comment by leidenglai** [comment]
模型文件用URL直接加载引用，比如可以另外起个静态服务器

**Comment by jiangming96** [comment]
![1bda124316f64b072bf5e901478670f5](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/87cbcf63-431d-40cb-b12f-537174c2b071)
![3036be7732058c16147983a0ec9189c8](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/27b15717-cec1-4bc9-8e8f-76c24dad1ed5)

我有尝试加载服务器上的模型 且通过浏览器可以正常下载模型，但依旧出现错误，可以给一个vue的例子么，index.vue.txt中为代码内容
[index.vue.txt](https://github.com/user-attachments/files/16141538/index.vue.txt)

**Comment by JMing96** [comment]
我有尝试加载服务器上的模型 且通过浏览器可以正常下载模型，但依旧出现错误，可以给一个vue的例子么，index.vue.txt中为代码内容
![5852203c8ff83d332dea339f4934d5b4](https://github.com/leidenglai/opencv-js-qrcode/assets/31053017/8bb4e63f-6222-4e33-90be-45b77c297b4f)

[index.vue.txt](https://github.com/user-attachments/files/16141804/index.vue.txt)

**Comment by leidenglai** [comment]
![image](https://github.com/leidenglai/opencv-js-qrcode/assets/11383747/5e6833d3-5df3-4cd1-88c5-e979e0c75aef)
我运行了你的代码，并没有报错

**Comment by JMing96** [comment]
> ![image](https://private-user-images.githubusercontent.com/11383747/347420222-5e6833d3-5df3-4cd1-88c5-e979e0c75aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjA1MzEsIm5iZiI6MTcyMDY2MDIzMSwicGF0aCI6Ii8xMTM4Mzc0Ny8zNDc0MjAyMjItNWU2ODMzZDMtNWRmMy00Y2QxLTg4YzUtZTk3OWUwYzc1YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAxMTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NzQxODFiNzI2MTk5MTEyMTEzODc3YjhkMWI4ZThmYzU1NzE1MTk2OTFjMTZhYmQ2NmE2NzM2MDY5NDkxYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P-hyPnnGiwOMyC6baDxVrMbt32K3A7jCi6YtwSOMR18) 我运行了你的代码，并没有报错

好的 我再排查下 感谢
