### ISSUE TITLE
请问在nodejs环境中可以使用吗？

### ISSUE THREAD

**Issue by LockVer** [leidenglai/opencv-js-qrcode#7]
我导入后提示找不到ImageData和Cannot read properties of undefined (reading 'detectAndDecode')错误

**Comment by leidenglai** [comment]
> 我导入后提示找不到ImageData和Cannot read properties of undefined (reading 'detectAndDecode')错误

需要支持WebAssembly，这是浏览器的能力；nodejs环境应该有更好的选择，作为服务端。

**Comment by LockVer** [comment]
试过使用其他库识别率没有wechat_qrcode好。。

**Comment by heyapeng1219** [comment]
> > 我导入后提示找不到ImageData和Cannot read properties of undefined (reading 'detectAndDecode')错误
> 
> 需要支持WebAssembly，这是浏览器的能力；nodejs环境应该有更好的选择，作为服务端。

node环境有没有什么好用的库

**Comment by leidenglai** [comment]
> > > 我导入后提示找不到ImageData和Cannot read properties of undefined (reading 'detectAndDecode')错误
> > 
> > 
> > 需要支持WebAssembly，这是浏览器的能力；nodejs环境应该有更好的选择，作为服务端。
> 
> node环境有没有什么好用的库

可以找找opencv相关的nodejs的库
